# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_from', models.CharField(max_length=500)),
                ('message_id', models.CharField(max_length=500)),
                ('sent_timestamp', models.CharField(max_length=500)),
                ('sent_to', models.CharField(max_length=500)),
                ('device_id', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
