# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='device_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='num_from',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_timestamp',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_to',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
